/*----- PROTECTED REGION ID(WebAuthTng2StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        WebAuthTng2StateMachine.cpp
//
// description : State machine file for the WebAuthTng2 class
//
// project :     Tango web authentication device server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <WebAuthTng2.h>

/*----- PROTECTED REGION END -----*/	//	WebAuthTng2::WebAuthTng2StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  
//  FAULT   |  


namespace WebAuthTng2_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : WebAuthTng2::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool WebAuthTng2::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(WebAuthTng2::OnStateAllowed) ENABLED START -----*/
    
    /*----- PROTECTED REGION END -----*/	//	WebAuthTng2::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : WebAuthTng2::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool WebAuthTng2::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(WebAuthTng2::OffStateAllowed) ENABLED START -----*/
    
    /*----- PROTECTED REGION END -----*/	//	WebAuthTng2::OffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : WebAuthTng2::is_check_permissions_allowed()
 *	Description : Execution allowed for check_permissions attribute
 */
//--------------------------------------------------------
bool WebAuthTng2::is_check_permissions_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for check_permissions command.
	/*----- PROTECTED REGION ID(WebAuthTng2::check_permissionsStateAllowed) ENABLED START -----*/
    
    /*----- PROTECTED REGION END -----*/	//	WebAuthTng2::check_permissionsStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : WebAuthTng2::is_check_user_allowed()
 *	Description : Execution allowed for check_user attribute
 */
//--------------------------------------------------------
bool WebAuthTng2::is_check_user_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for check_user command.
	/*----- PROTECTED REGION ID(WebAuthTng2::check_userStateAllowed) ENABLED START -----*/
    
    /*----- PROTECTED REGION END -----*/	//	WebAuthTng2::check_userStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : WebAuthTng2::is_Send_log_command_ex_allowed()
 *	Description : Execution allowed for Send_log_command_ex attribute
 */
//--------------------------------------------------------
bool WebAuthTng2::is_Send_log_command_ex_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Send_log_command_ex command.
	/*----- PROTECTED REGION ID(WebAuthTng2::Send_log_command_exStateAllowed) ENABLED START -----*/
    
    /*----- PROTECTED REGION END -----*/	//	WebAuthTng2::Send_log_command_exStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : WebAuthTng2::is_check_user_ident_allowed()
 *	Description : Execution allowed for check_user_ident attribute
 */
//--------------------------------------------------------
bool WebAuthTng2::is_check_user_ident_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for check_user_ident command.
	/*----- PROTECTED REGION ID(WebAuthTng2::check_user_identStateAllowed) ENABLED START -----*/
    
    /*----- PROTECTED REGION END -----*/	//	WebAuthTng2::check_user_identStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : WebAuthTng2::is_check_permissions_www_allowed()
 *	Description : Execution allowed for check_permissions_www attribute
 */
//--------------------------------------------------------
bool WebAuthTng2::is_check_permissions_www_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for check_permissions_www command.
	/*----- PROTECTED REGION ID(WebAuthTng2::check_permissions_wwwStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	WebAuthTng2::check_permissions_wwwStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(WebAuthTng2::WebAuthTng2StateAllowed.AdditionalMethods) ENABLED START -----*/

//    Additional Methods

/*----- PROTECTED REGION END -----*/	//	WebAuthTng2::WebAuthTng2StateAllowed.AdditionalMethods

}	//	End of namespace
